### ISSUE TITLE
Unpositioned tree in specs2

### ISSUE THREAD

**Issue by MasseGuillaume** [non/kind-projector#7] opened 2015-01-28 16:35 UTC
Hi Erik,

kind-projector is breaking positions for specs2 specification macros

```
sbt test
[info] Loading project definition from /Users/gmasse1/Projects/bug-pos/project
[info] Set current project to bug-pos (in build file:/Users/gmasse1/Projects/bug-pos/)
[info] Compiling 1 Scala source to /Users/gmasse1/Projects/bug-pos/target/scala-2.11/test-classes...
[info] ======= Position error
[info] Unpositioned tree #931
[info]    unpositioned [L   0 P#  932] #931    [NoPosition]    Template   // Template(value <local ASpec>)
[info]       enclosing [L   4        ] #932    [35:128]        ClassDef   // ASpec extends Specification { def is = s2"""
[info]         sibling [L   0 P#  932] #931    [NoPosition]    Template   // Template(value <local ASpec>)
[info] 
[info] While validating #933
[info] [L   1        ] #933    [0:128]         PackageDef // import TTFI._
[info] 
[info] Children:
[info]   [L   1 P#  933] #52     [0:0]           Ident      // i
[info]   [L   1 P#  933] #24     [0:13]          Import     // TTFI._
[info]   [L   3 P#  933] #27     [15:34]         Import     // org.specs2._
[info]   [L   4 P#  933] #932    [35:128]        ClassDef   // ASpec extends Specification { def is = s2"""
[info] =======
scala.reflect.internal.Positions$ValidateException: Unpositioned tree #931
	at scala.reflect.internal.Positions$class.positionError$1(Positions.scala:102)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:112)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions$class.validatePositions(Positions.scala:147)
	at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:16)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:103)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:441)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:432)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1580)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:167)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:96)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:144)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:39)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
	at sbt.inc.Incremental$.compile(Incremental.scala:38)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:158)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
	at sbt.Compiler$.apply(Compiler.scala:101)
	at sbt.Compiler$.apply(Compiler.scala:87)
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:789)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (test:compile) scala.reflect.internal.Positions$ValidateException: Unpositioned tree #931
[error] Total time: 2 s, completed 28-Jan-2015 11:34:09 AM
```

comment out https://github.com/MasseGuillaume/kind-projector-specs2-bug/blob/e2517440ee29c6fb47125fd8c2f677db6ee726e4/build.sbt#L9

```
sbt test
[info] Loading project definition from /Users/gmasse1/Projects/bug-pos/project
[info] Set current project to bug-pos (in build file:/Users/gmasse1/Projects/bug-pos/)
[info] Updating {file:/Users/gmasse1/Projects/bug-pos/}bug-pos...
[info] Resolving jline#jline;2.12 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/gmasse1/Projects/bug-pos/target/scala-2.11/test-classes...
[info] ASpec
[info] * wip PENDING
[info] 
[info] Total for specification ASpec
[info] Finished in 12 ms
[info] 1 example, 0 failure, 0 error, 1 pending
[info]  
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0, Pending 1
[success] Total time: 4 s, completed 28-Jan-2015 11:34:59 AM
```

**Comment by non** [comment] 2015-01-28 17:18
Ouch! OK, I'll try to look into this.

If you get a chance to look at the particular file this error comes from it might be helpful to try to come up with a minimal test case. This is what I plan to do when I get a chance (hopefully before nescala).

**Comment by MasseGuillaume** [comment] 2015-01-28 18:13
I suspect https://github.com/etorreborre/specs2/blob/SPECS2-2.4.15/core/src/main/scala/org/specs2/specification/SpecificationStringContext.scala#L120

because if I comment out range pos at https://github.com/MasseGuillaume/kind-projector-specs2-bug/blob/e2517440ee29c6fb47125fd8c2f677db6ee726e4/build.sbt#L5 I dont have any error after running `sbt test`

**Comment by MasseGuillaume** [comment] 2015-01-28 18:15
@etorreborre ping

**Comment by non** [comment] 2015-01-28 18:31
It might also be the case that I'm not handling range positions correctly. I'll try some basic tests with `-Yrangepos` to ensure that things work properly in that case.

**Comment by etorreborre** [comment] 2015-01-28 22:04
It might be a `-Yrangepos` issue. I have observed such issues with `-Yrangepos` and they disappear when I remove the option. But the option is really useful! It allows me to precisely capture code that is nested inside an interpolated string.

**Comment by sellout** [comment] 2015-03-02 18:37
My case seems to involve neither `-Yrangepos` nor specs2 (as it happens while compiling to “classes”, not “test-classes”).

**Comment by sellout** [comment] 2015-03-02 18:56
Ah – turning on scoverage is what does it for us (which is why my non-CI builds weren’t hitting it).

**Comment by sellout** [comment] 2015-03-02 19:03
Disabling `coverageHighlighting` (which enables `-Yrangepos`) fixes my build, so that seems very likely to be the culprit.

**Comment by adelbertc** [comment] 2015-03-12 03:58
Seems Specs 2 3.0.1 doesn't play nice with kind-projector. Turning on `-Yrangepos` gives me the error described above, turning it off with 3.0.1 gives me:

```
exception during macro expansion:
[error] java.lang.UnsupportedOperationException: Position.end on class scala.reflect.internal.util.OffsetPosition
[error] 	at scala.reflect.internal.util.Position.end(Position.scala:126)
[error] 	at org.specs2.specification.create.S2Macro$$anonfun$2.apply(S2Macro.scala:26)
[error] 	at org.specs2.specification.create.S2Macro$$anonfun$2.apply(S2Macro.scala:26)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error] 	at scala.collection.immutable.List.foreach(List.scala:318)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[error] 	at org.specs2.specification.create.S2Macro$.s2Implementation(S2Macro.scala:26)
[error]     s2"""
[error]     ^
```

If I change to Specs2 2.4.17 however, it's all good.

**Comment by etorreborre** [comment] 2015-03-12 04:57
@adelbertc this is a regression from 2.4.17, I'll fix that and get back to you.

**Comment by etorreborre** [comment] 2015-03-12 05:41
@adelbertc I can't actually reproduce the problem with 3.0.1 but I trust you because I've seen it yesterday. Can you please try [3.0.1-20150312050040-d541934](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.0.1-20150312050040-d541934/)?

**Comment by adelbertc** [comment] 2015-03-12 06:28
@etorreborre OK I'm a bit weirded out. Seems on 2.11 w/ 3.0.1-20150312050040-d541934 it's all good. Then I tried 3.0.1 again and it was still good. Then I ran a `+ test` and it broke on 2.10.. maybe it's 2.10 specific?

**Comment by etorreborre** [comment] 2015-03-12 10:24
@adelbertc I observed the same thing. Can you confirm that 3.0.1-20150312050040-d541934 works on Scala 2.10? (I can't do that at the moment)

**Comment by etorreborre** [comment] 2015-03-12 13:09
I get it. I fixed the issue for Scala 2.11 but forgot to fix it for 2.10. My macro code is kinda duplicated in 2 source directories, one per Scala version to deal with warnings. I fixed one but not the other. You can now use `specs2-core_2.10-3.0.1-20150312124001-4835e88` if you need Scala 2.10.

**Comment by adelbertc** [comment] 2015-03-12 18:27
@etorreborre Got it, thanks! I'll hang on to 2.4.17 in the interim while I await 3.0.2 :-)

**Comment by MasseGuillaume** [comment] 2015-04-10 18:52
@etorreborre same issue with 3.4

**Comment by MasseGuillaume** [comment] 2015-04-10 19:01
my current is to not mix kind-projector and specs2:
```scala
addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.5.2")
scalacOptions in Test := Seq("-Yrangepos")
```

**Comment by non** [comment] 2015-04-10 19:04
Yeah sorry, I need to look into this more but haven't had a chance.

**Comment by MasseGuillaume** [comment] 2015-04-10 19:10
@non @etorreborre have you guys consider using scalameta ?

ping: @xeno-by

**Comment by xeno-by** [comment] 2015-04-10 21:04
@MasseGuillaume what would be the use case for scala.meta here? Do you mean reproducing some particular piece of existing functionality in a different way or replacing the entire plugin with something else?

**Comment by MasseGuillaume** [comment] 2015-04-10 21:30
@xeno-by the kind-projector plugin and the `is` macro in specs2 are conflicting.

@non compiler plugins change the parser phase, is it possible to with scala meta ?

@etorreborre look like he's using macro pretty intensely  in specs2, is it possible to rewrite it to use scalameta ?

**Comment by etorreborre** [comment] 2015-04-13 00:30
@MasseGuillaume I am just using a macro to catch in an interpolated string the "non-text" parts. I don't know if it is possible to rewrite it using scala.meta but if string interpolation could be enhanced so that the `StringContext` gives all information about the interpolated string, that would be enough for me. In particular I need the location of all the "parts" and "non-parts" (or just deduce one from the other).

**Comment by xeno-by** [comment] 2015-04-13 10:41
@MasseGuillaume Customizing Scala syntax with scala.meta is a non-goal for now. There are some really interesting ideas, but it's hard to say when/if they materialize.

Supporting macros is a goal for scala.meta, but we're still too early in development to accommodate these use cases. It'll become clearer in Amsterdam (at ScalaDays).

**Comment by non** [comment] 2015-05-06 22:34
So, I'm looking at this in detail finally.

Like the bug reports suggest, kind-projector is producing trees with no position. This isn't surprising since I didn't make any effort to track the old positions and update the new synthetic trees with them.

However, I don't see an obvious API for me to create trees that have valid range positions. I'll try looking through the code and asking around, but as far as I can tell, the chain goes like this.

First, I need for the trees I generate to have a `pos` method that returns something other than `NoPosition`. However, the constructors I have access to don't seem to take `Position` arguments. Where does this come from?

```scala
// src/reflect/scala/reflect/internal/Trees.scala
abstract class Tree extends ... {
  ...
  final override def pos: Position = rawatt.pos
  ...
}
```

Alright, great. So it looks like the intention is that I need to mutably update `rawatt` somehow? Let's look for that:

```scala
// src/reflect/scala/reflect/internal/StdAttachments.scala
trait Attachable {
  protected var rawatt: scala.reflect.macros.Attachments { type Pos = Position } = NoPosition
  ...
}
```

So... well... um.

I'm not sure how to proceed. It doesn't look like there's an obvious way for me to provide range positions (assuming I was collecting them in the first place).

If anyone out there has a suggestion on what I should be doing here I'm happy to take it -- no idea too outlandish! :tropical_fish:

**Comment by retronym** [comment] 2015-05-07 01:22
@non `Tree#pos_= ` allows you to mutate the position of a tree.

**Comment by non** [comment] 2015-05-07 02:00
Aha! Thanks @retronym!

I'll start experimenting and see if I can't get this working after all.

**Comment by retronym** [comment] 2015-05-07 02:11
https://github.com/non/kind-projector/pull/10

**Closed** 2015-05-07 02:15 UTC

**Comment by etorreborre** [comment] 2015-05-07 05:04
Thanks @retronym! @non can we expect a release soon?

**Comment by non** [comment] 2015-05-07 05:41
I just released version 0.5.4 to Bintray.

I tested it with @MasseGuillaume's sample project and it worked fine.

Thanks again to @retronym for the help!

**Comment by MasseGuillaume** [comment] 2015-05-07 09:58
wunderbar! Thanks!

**Comment by sellout** [comment] 2015-05-09 02:47
Thanks, @non / @retronym!
